
from fastapi import APIRouter
from fastapi.responses import StreamingResponse

from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

router = APIRouter(prefix="/report", tags=["Report"])


@router.post("/pdf")
async def generate_pdf(data: dict):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        alignment=TA_CENTER,
        textColor=HexColor("#2563EB"),
        fontSize=24,
        spaceAfter=18,
    )

    heading_style = ParagraphStyle(
        "Heading",
        parent=styles["Heading2"],
        textColor=HexColor("#1D4ED8"),
        spaceBefore=12,
        spaceAfter=8,
    )

    score_style = ParagraphStyle(
        "Score",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=34,
        textColor=HexColor("#16A34A"),
        spaceAfter=10,
    )

    elements = []

    # Title
    elements.append(
        Paragraph("HireSense-AI Resume Analysis Report", title_style)
    )

    elements.append(
        Paragraph(
            datetime.now().strftime("%d %B %Y %H:%M"),
            styles["Normal"],
        )
    )

    elements.append(Spacer(1, 20))

    # Candidate Table
    table_data = [
        ["Candidate", data.get("name", "Unknown")],
        ["ATS Score", f"{data.get('ats_score',0)} %"],
        ["Verdict", data.get("verdict", "-")],
    ]

    table = Table(table_data, colWidths=[120, 300])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (0,-1), HexColor("#DBEAFE")),
            ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
            ("BOTTOMPADDING", (0,0), (-1,-1), 8),
            ("TOPPADDING", (0,0), (-1,-1), 8),
        ])
    )

    elements.append(table)

    elements.append(Spacer(1, 25))

    # ATS Score
    elements.append(Paragraph("ATS SCORE", heading_style))
    elements.append(
        Paragraph(
            f"{data.get('ats_score',0)}%",
            score_style,
        )
    )

    elements.append(Spacer(1,15))

    sections = [
        ("Summary", data.get("summary","No summary available")),
        ("Strengths", data.get("strengths",[])),
        ("Weaknesses", data.get("weaknesses",[])),
        ("Missing Skills", data.get("missing_skills",[])),
        ("Priority Suggestions", data.get("suggestions",[])),
    ]

    for title, content in sections:

        elements.append(Paragraph(title, heading_style))

        if isinstance(content, list):
            if len(content) == 0:
                elements.append(
                    Paragraph("None", styles["BodyText"])
                )
            else:
                for item in content:
                    elements.append(
                        Paragraph(f"• {item}", styles["BodyText"])
                    )
        else:
            elements.append(
                Paragraph(content, styles["BodyText"])
            )

        elements.append(Spacer(1,10))

    elements.append(Spacer(1,20))

    elements.append(
        Paragraph(
            "<b>Generated by HireSense-AI</b>",
            styles["Normal"],
        )
    )

    doc.build(elements)

    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition":
            "attachment; filename=HireSense_AI_Report.pdf"
        },
    )